import 'dart:convert';
import 'dart:io';
import 'package:archive/archive.dart';
import 'package:http/http.dart' as http;
import 'package:path/path.dart' as p;
import '../domain/installed_addon.dart';
import 'addon_manifest_parser.dart';
class AddonInstallException implements Exception { const AddonInstallException(this.message); final String message; @override String toString()=>'AddonInstallException: $message'; }
class AddonPackageInstaller {
 AddonPackageInstaller({http.Client? client,this.manifestParser=const AddonManifestParser()}):_client=client??http.Client(),_ownsClient=client==null;
 static const int _maxDownloadBytes=256*1024*1024,_maxExpandedBytes=512*1024*1024; final http.Client _client;final bool _ownsClient;final AddonManifestParser manifestParser;
 Future<InstalledAddon> installFromUri({required Uri packageUri,required Directory addonsRoot,String? expectedAddonId,String? expectedVersion}) async {final r=await _client.get(packageUri,headers:const {'User-Agent':'AddKo/0.1.0'});if(r.statusCode<200||r.statusCode>=300)throw AddonInstallException('HTTP ${r.statusCode} ao baixar $packageUri.');if(r.bodyBytes.length>_maxDownloadBytes)throw const AddonInstallException('O pacote ultrapassa o limite de download de 256 MB.');return installBytes(bytes:r.bodyBytes,addonsRoot:addonsRoot,expectedAddonId:expectedAddonId,expectedVersion:expectedVersion);}
 Future<InstalledAddon> installBytes({required List<int> bytes,required Directory addonsRoot,String? expectedAddonId,String? expectedVersion}) async {if(bytes.isEmpty)throw const AddonInstallException('O pacote ZIP está vazio.');Archive archive;try{archive=ZipDecoder().decodeBytes(bytes,verify:true);}on Object catch(e){throw AddonInstallException('ZIP inválido: $e');}final mf=_findManifest(archive);final manifest=manifestParser.parse(_decodeArchiveFile(mf.file));if(expectedAddonId!=null&&manifest.id!=expectedAddonId)throw AddonInstallException('O pacote baixado declara ${manifest.id}, mas era esperado $expectedAddonId.');if(expectedVersion!=null&&manifest.version!=expectedVersion)throw AddonInstallException('O pacote ${manifest.id} declara versão ${manifest.version}, mas o índice anunciou $expectedVersion.');if(!RegExp(r'^[A-Za-z0-9._-]+$').hasMatch(manifest.id))throw AddonInstallException('O id do addon contém caracteres inseguros: ${manifest.id}');final expanded=archive.files.fold<int>(0,(s,f)=>s+(f.isFile?f.size:0));if(expanded>_maxExpandedBytes)throw const AddonInstallException('O conteúdo expandido do pacote ultrapassa 512 MB.');await addonsRoot.create(recursive:true);final stamp=DateTime.now().microsecondsSinceEpoch;final staging=Directory(p.join(addonsRoot.path,'.staging-${manifest.id}-$stamp'));final target=Directory(p.join(addonsRoot.path,manifest.id));final backup=Directory(p.join(addonsRoot.path,'.backup-${manifest.id}-$stamp'));try{await staging.create(recursive:true);await _extractArchive(archive:archive,rootPrefix:mf.rootPrefix,destination:staging);if(!await File(p.join(staging.path,'addon.xml')).exists())throw const AddonInstallException('O pacote não gerou addon.xml na raiz do addon.');if(await target.exists())await target.rename(backup.path);try{await staging.rename(target.path);}on Object{if(await backup.exists()&&!await target.exists())await backup.rename(target.path);rethrow;}if(await backup.exists())await backup.delete(recursive:true);return InstalledAddon(manifest:manifest,installPath:target.path);}on AddonInstallException{rethrow;}on Object catch(e){throw AddonInstallException('Falha ao instalar ${manifest.id}: $e');}finally{if(await staging.exists())await staging.delete(recursive:true);if(await backup.exists()&&await target.exists())await backup.delete(recursive:true);}}
 _ManifestArchiveFile _findManifest(Archive archive){final candidates=<_ManifestArchiveFile>[];for(final f in archive.files){if(!f.isFile)continue;final n=f.name.replaceAll('\\','/');if(n=='addon.xml')candidates.add(_ManifestArchiveFile(file:f,rootPrefix:''));else if(n.endsWith('/addon.xml'))candidates.add(_ManifestArchiveFile(file:f,rootPrefix:n.substring(0,n.length-'/addon.xml'.length)));}if(candidates.isEmpty)throw const AddonInstallException('O ZIP não contém addon.xml.');candidates.sort((a,b)=>_depth(a.rootPrefix).compareTo(_depth(b.rootPrefix)));return candidates.first;}
 Future<void> _extractArchive({required Archive archive,required String rootPrefix,required Directory destination}) async {final prefix=rootPrefix.isEmpty?'':'$rootPrefix/';for(final f in archive.files){var n=f.name.replaceAll('\\','/');if(prefix.isNotEmpty){if(!n.startsWith(prefix))continue;n=n.substring(prefix.length);}if(n.isEmpty)continue;final safe=_safeRelativePath(n);if(safe==null)throw AddonInstallException('O ZIP contém um caminho inseguro: ${f.name}');final out=p.join(destination.path,safe);if(f.isFile){final file=File(out);await file.parent.create(recursive:true);await file.writeAsBytes(List<int>.from(f.content as List<int>),flush:true);}else{await Directory(out).create(recursive:true);}}}
 String? _safeRelativePath(String v){final n=p.posix.normalize(v.replaceAll('\\','/'));if(n=='.'||n.startsWith('../')||n=='..'||n.startsWith('/')||p.posix.isAbsolute(n))return null;final seg=p.posix.split(n);if(seg.any((s)=>s=='..'||s.isEmpty))return null;return p.joinAll(seg);}
 String _decodeArchiveFile(ArchiveFile f){try{return utf8.decode(List<int>.from(f.content as List<int>));}on Object catch(e){throw AddonInstallException('addon.xml não está em UTF-8 válido: $e');}}
 int _depth(String pfx)=>pfx.isEmpty?0:pfx.split('/').where((s)=>s.isNotEmpty).length; void close(){if(_ownsClient)_client.close();}
}
class _ManifestArchiveFile{const _ManifestArchiveFile({required this.file,required this.rootPrefix});final ArchiveFile file;final String rootPrefix;}
