#!/usr/bin/env python3
"""Vendor the exact Kodi Omega API/ABI source used by AddKo.

This tool is intentionally separate from the normal Android build. It is used
when updating AddKo's compatibility layer so API names, signatures, constants
and binary add-on ABI structures come from Kodi Omega instead of being guessed.
"""

from __future__ import annotations

import hashlib
import json
import urllib.request
from pathlib import Path

KODI_REPOSITORY = "https://raw.githubusercontent.com/xbmc/xbmc"
KODI_COMMIT = "f8815ee40f49a700c047982d752be4b2a61420e2"

PYTHON_API_FILES = (
    # Kodi Omega SWIG modules. Keep this list complete: these are the seven
    # Python modules generated by xbmc/interfaces/swig/CMakeLists.txt.
    "xbmc/interfaces/swig/AddonModuleXbmc.i",
    "xbmc/interfaces/swig/AddonModuleXbmcaddon.i",
    "xbmc/interfaces/swig/AddonModuleXbmcdrm.i",
    "xbmc/interfaces/swig/AddonModuleXbmcgui.i",
    "xbmc/interfaces/swig/AddonModuleXbmcplugin.i",
    "xbmc/interfaces/swig/AddonModuleXbmcvfs.i",
    "xbmc/interfaces/swig/AddonModuleXbmcwsgi.i",
    # Legacy headers used by those bindings.
    "xbmc/interfaces/legacy/ModuleXbmc.h",
    "xbmc/interfaces/legacy/ModuleXbmcgui.h",
    "xbmc/interfaces/legacy/ModuleXbmcplugin.h",
    "xbmc/interfaces/legacy/ModuleXbmcvfs.h",
    "xbmc/interfaces/legacy/Addon.h",
    "xbmc/interfaces/legacy/Settings.h",
    "xbmc/interfaces/legacy/Dialog.h",
    "xbmc/interfaces/legacy/Keyboard.h",
    "xbmc/interfaces/legacy/ListItem.h",
    "xbmc/interfaces/legacy/Player.h",
    "xbmc/interfaces/legacy/PlayList.h",
    "xbmc/interfaces/legacy/Monitor.h",
    "xbmc/interfaces/legacy/Window.h",
    "xbmc/interfaces/legacy/WindowXML.h",
    "xbmc/interfaces/legacy/Control.h",
    "xbmc/interfaces/legacy/File.h",
    "xbmc/interfaces/legacy/Stat.h",
    "xbmc/interfaces/legacy/DrmCryptoSession.h",
    "xbmc/interfaces/legacy/wsgi/WsgiErrorStream.h",
    "xbmc/interfaces/legacy/wsgi/WsgiInputStream.h",
    "xbmc/interfaces/legacy/wsgi/WsgiResponse.h",
    "xbmc/interfaces/legacy/wsgi/WsgiResponseBody.h",
)

BINARY_ABI_FILES = (
    # Global Kodi binary add-on API/ABI.
    "xbmc/addons/kodi-dev-kit/include/kodi/versions.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/AddonBase.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/General.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/Filesystem.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/Network.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon_base.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/filesystem.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/network.h",
    # Every Kodi Omega binary instance type.
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/audiodecoder.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/audioencoder.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/game.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/imagedecoder.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/inputstream.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/peripheral.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/screensaver.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/vfs.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/video_codec.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/visualization.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/addon-instance/AudioDecoder.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/addon-instance/AudioEncoder.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/addon-instance/Game.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/addon-instance/ImageDecoder.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/addon-instance/Inputstream.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/addon-instance/Peripheral.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/addon-instance/PVR.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/addon-instance/Screensaver.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/addon-instance/VFS.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/addon-instance/VideoCodec.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/addon-instance/Visualization.h",
    # InputStream structures required by inputstream.adaptive and other
    # demuxing add-ons.
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/inputstream/demux_packet.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/inputstream/stream_codec.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/inputstream/stream_constants.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/inputstream/stream_crypto.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/inputstream/timing_constants.h",
    # PVR's instance header is split into these public structures.
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr/pvr_providers.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr/pvr_channel_groups.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr/pvr_channels.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr/pvr_defines.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr/pvr_edl.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr/pvr_epg.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr/pvr_general.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr/pvr_menu_hook.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr/pvr_recordings.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr/pvr_stream.h",
    "xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr/pvr_timers.h",
    "xbmc/addons/binary-addons/DllAddon.h",
)

FILES = (*PYTHON_API_FILES, *BINARY_ABI_FILES)


def root() -> Path:
    return Path(__file__).resolve().parents[1]


def download(relative: str, destination: Path) -> str:
    url = f"{KODI_REPOSITORY}/{KODI_COMMIT}/{relative}"
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "AddKo-Kodi-vendor/1.0"},
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        data = response.read()
    if not data:
        raise RuntimeError(f"Kodi returned an empty file for {relative}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(data)
    return hashlib.sha256(data).hexdigest()


def main() -> int:
    destination_root = root() / "third_party" / "kodi_omega" / "upstream"
    manifest: dict[str, object] = {
        "repository": "https://github.com/xbmc/xbmc",
        "commit": KODI_COMMIT,
        "license": "GPL-2.0-or-later",
        "python_api_files": len(PYTHON_API_FILES),
        "binary_abi_files": len(BINARY_ABI_FILES),
        "files": {},
    }

    for relative in FILES:
        destination = destination_root / relative
        digest = download(relative, destination)
        manifest["files"][relative] = {  # type: ignore[index]
            "sha256": digest,
            "bytes": destination.stat().st_size,
        }
        print(f"[AddKo] Kodi Omega: {relative}")

    manifest_path = root() / "third_party" / "kodi_omega" / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    print(f"[AddKo] Kodi Omega API/ABI snapshot written to {destination_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
